[[tables]]
name = "users"
path = "example/data/users.csv"
columns = [
	{ name = "id",   data_type = "Int128", options = ["NotNull"] },
	{ name = "name", data_type = "Text",   options = ["NotNull"] },
	{ name = "age",  data_type = "Uint8",  options = []          },
	{ name = "role", data_type = "Text",   options = ["NotNull"] },
]
