[[tables]]
name = "users"
path = "example/data/users.csv"
columns = [
	{ name = "id",   data_type = "Int128", options = [{ option = "NotNull" }] },
	{ name = "name", data_type = "Text",   options = [{ option = "NotNull" }] },
	{ name = "age",  data_type = "Uint8",  options = []                       },
	{ name = "role", data_type = "Text",   options = [{ option = "NotNull" }] },
]
