[package]
authors = ["Taehoon Moon <taehoon.moon@outlook.com>"]
description = "GlueSQL - Open source SQL database engine fully written in Rust with pure functional execution layer, easily swappable storage and web assembly support!"
documentation = "https://docs.rs/gluesql/"
edition = "2021"
license = "Apache-2.0"
name = "gluesql-core"
repository = "https://github.com/gluesql/gluesql"
version = "0.10.2"

[dependencies]
utils = {package = "gluesql-utils", path = "../utils", version = "0.10.2"}

async-recursion = "1"
async-trait = "0.1"
bigdecimal = {version = "0.3", features = ["serde", "string-only"]}
cfg-if = "1"
chrono = {version = "0.4", features = ["serde", "wasmbind"]}
futures = "0.3"
im-rc = "15"
iter-enum = "1"
itertools = "0.10"
regex = "1"
rust_decimal = {version = "1", features = ["serde-str"]}
serde = {version = "1", features = ["derive"]}
serde_json = "1"
sqlparser = {version = "0.13", features = ["serde", "bigdecimal"]}
strum_macros = "0.23"
thiserror = "1.0"
uuid = {version = "0.8", features = ["v4"]}

[features]
# optional: ALTER TABLE
# you can include whether ALTER TABLE support or not for your custom database implementation.
alter-table = []

# optional: INDEX
index = []

# optional: TRANSACTION
transaction = []

# optional: METADATA
# e.g. SHOW TABLES;
metadata = []
